name: Test_CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Test:
    name: Test_CO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Python_version
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mi prueba unitaria
        run: pytest


